const goodsData = [
  {
    goodImg: "src/assets/img/goods/goods-img.png",
    title: "同庆楼|中华老字号",
    score: "4.7",
    salesNumber: "1000+",
    aPrice: "20",
    type: "美团专送",
    start: "20",
    expressPrice: "0",
    time: "29",
    distant: "1.0",
    comment: ["精选好店", "40人觉得分量足"],
    promotion: ["天天神券"],
    promotion2: ["28减2", "39减5", "65减8"],
    goodsGroup: [
      {
        groupId: 1,
        categoryId: 1,
        categoryName: "收藏福利",
        goods: [
          {
            name: "绿豆汤（位）",
            salesMonth: "300+",
            comment: "90%",
            price: "8",
            tag: "门店销量第2名",
            goodImg: "src/assets/img/shop/goods1.png",
          },
          {
            name: "虾仁蒸蛋（位）",
            salesMonth: "300+",
            comment: "100%",
            price: "5",
            tag: '`"鲜嫩爽滑"`',
            goodImg: "src/assets/img/shop/goods2.png",
          },
        ],
      },
      {
        groupId: 2,
        categoryId: 2,
        categoryName: "同庆必点",
        goods: [
          {
            name: "同庆楼狮子头（个）",
            salesMonth: "100+",
            comment: "100%",
            price: "9",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods4.png",
          },
          {
            name: "招聘红烧肉",
            salesMonth: "100+",
            comment: "100%",
            price: "9",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "深井烤鸭（中份）",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "湖南辣椒炒肉",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "招聘烤鸭",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "烤脆皮鸡",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "老谭酸菜鱼）",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods3.png",
          },
        ],
      },
      {
        groupId: 3,
        categoryId: 3,
        categoryName: "超值套餐新品上市",
        goods: [
          {
            name: "鱼香肉丝+小炒酸豆角+蒸蛋+番茄+例汤",
            salesMonth: "100+",
            comment: "100%",
            price: "32",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods4.png",
          },
          {
            name: "招聘红烧肉",
            salesMonth: "100+",
            comment: "100%",
            price: "9",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "深井烤鸭（中份）",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods1.png",
          },
          {
            name: "湖南辣椒炒肉",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods2.png",
          },
        ],
      },
      {
        groupId: 4,
        categoryId: 4,
        categoryName: "同庆小份菜",
        goods: [
          {
            name: "小炒花菜",
            salesMonth: "100+",
            comment: "100%",
            price: "32",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods4.png",
          },
          {
            name: "湖南小炒肉",
            salesMonth: "100+",
            comment: "100%",
            price: "9",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "深井烤鸭（中份）",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods1.png",
          },
        ],
      },
      {
        groupId: 5,
        categoryId: 5,
        categoryName: "同庆上新",
        goods: [
          {
            name: "鸡丝凉面",
            salesMonth: "100+",
            comment: "100%",
            price: "32",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods4.png",
          },
          {
            name: "湖南小炒肉",
            salesMonth: "100+",
            comment: "100%",
            price: "9",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "深井烤鸭（中份）",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods1.png",
          },
        ],
      },
      {
        groupId: 6,
        categoryId: 6,
        categoryName: "大厨现炒",
        goods: [
          {
            name: "外婆菜炒鸡蛋",
            salesMonth: "100+",
            comment: "100%",
            price: "32",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods4.png",
          },
          {
            name: "湖南小炒肉",
            salesMonth: "100+",
            comment: "100%",
            price: "9",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "深井烤鸭（中份）",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods1.png",
          },
        ],
      },
      {
        groupId: 7,
        categoryId: 7,
        categoryName: "家常甄选",
        goods: [
          {
            name: "外婆菜炒鸡蛋",
            salesMonth: "100+",
            comment: "100%",
            price: "32",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods4.png",
          },
          {
            name: "湖南小炒肉",
            salesMonth: "100+",
            comment: "100%",
            price: "9",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "深井烤鸭（中份）",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods1.png",
          },
        ],
      },
      {
        groupId: 8,
        categoryId: 8,
        categoryName: "清炒时蔬",
        goods: [
          {
            name: "外婆菜炒鸡蛋",
            salesMonth: "100+",
            comment: "100%",
            price: "32",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods4.png",
          },
          {
            name: "湖南小炒肉",
            salesMonth: "100+",
            comment: "100%",
            price: "9",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "深井烤鸭（中份）",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods1.png",
          },
        ],
      },
      {
        groupId: 9,
        categoryId: 9,
        categoryName: "热辣湘菜",
        goods: [
          {
            name: "外婆菜炒鸡蛋",
            salesMonth: "100+",
            comment: "100%",
            price: "32",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods4.png",
          },
          {
            name: "湖南小炒肉",
            salesMonth: "100+",
            comment: "100%",
            price: "9",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "深井烤鸭（中份）",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods1.png",
          },
        ],
      },
      {
        groupId: 10,
        categoryId: 10,
        categoryName: "想吃好点",
        goods: [
          {
            name: "外婆菜炒鸡蛋",
            salesMonth: "100+",
            comment: "100%",
            price: "32",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods4.png",
          },
          {
            name: "湖南小炒肉",
            salesMonth: "100+",
            comment: "100%",
            price: "9",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods3.png",
          },
          {
            name: "深井烤鸭（中份）",
            salesMonth: "85",
            comment: "90%",
            price: "28",
            tag: "",
            goodImg: "src/assets/img/shop/goods1.png",
          },
        ],
      },
      {
        groupId: 11,
        categoryId: 11,
        categoryName: "同庆主食",
        goods: [
          {
            name: "米饭",
            salesMonth: "100+",
            comment: "100%",
            price: "2",
            tag: "",
            goodImg: "src/assets/img/shop/goods4.png",
          },
          {
            name: "扬州炒饭",
            salesMonth: "100+",
            comment: "100%",
            price: "15",
            tag: "",
            goodImg: "src/assets/img/shop/goods3.png",
          },
        ],
      },
      {
        groupId: 12,
        categoryId: 12,
        categoryName: "同庆点心",
        goods: [
          {
            name: "香煎萝卜饼",
            salesMonth: "100+",
            comment: "100%",
            price: "4",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods4.png",
          },
          {
            name: "水晶蒸虾饺皇",
            salesMonth: "100+",
            comment: "100%",
            price: "9",
            tag: "店内好评第1名",
            goodImg: "src/assets/img/shop/goods3.png",
          },
        ],
      },
    ],
    category: [
      {
        id: 1,
        name: "收藏福利",
      },
      {
        id: 2,
        name: "同庆必点",
      },
      {
        id: 3,
        name: "超值套餐新品上市",
      },
      {
        id: 4,
        name: "同庆小份菜",
      },
      {
        id: 5,
        name: "同庆上新",
      },
      {
        id: 6,
        name: "大厨现炒",
      },
      {
        id: 7,
        name: "家常甄选",
      },
      {
        id: 8,
        name: "清炒时蔬",
      },
      {
        id: 9,
        name: "热辣湘菜",
      },
      {
        id: 10,
        name: "想吃好点",
      },
      {
        id: 11,
        name: "同庆主食",
      },
      {
        id: 12,
        name: "同庆点心",
      },
    ],
  },
  {
    goodImg: "src/assets/img/goods/goods-img2.png",
    title: "鲜丰水果",
    score: "4.9",
    salesNumber: "1000+",
    aPrice: "20",
    type: "美团快送",
    start: "20",
    expressPrice: "1.5",
    time: "49",
    distant: "6.7",
    comment: ["精选好店", "40人觉得分量足"],
    promotion: ["0.01元爆品", "56折起"],
  },
  {
    goodImg: "src/assets/img/goods/goods-img3.png",
    title: "顺旺基",
    score: "4.4",
    salesNumber: "3000+",
    aPrice: "20",
    type: "美团专送",
    start: "20",
    expressPrice: "0",
    time: "49",
    distant: "6.7",
    comment: ["还会再来", "包装精致"],
    promotion2: ["28减2", "39减5", "65减8"],
  },
  {
    goodImg: "src/assets/img/goods/goods-img3.png",
    title: "顺旺基2",
    score: "4.4",
    salesNumber: "3000+",
    aPrice: "20",
    type: "美团专送",
    start: "20",
    expressPrice: "0",
    time: "49",
    distant: "6.7",
    comment: ["还会再来", "包装精致"],
    promotion2: ["28减2", "39减5", "65减8"],
  },
  {
    goodImg: "src/assets/img/goods/goods-img3.png",
    title: "顺旺基3",
    score: "4.4",
    salesNumber: "3000+",
    aPrice: "20",
    type: "美团专送",
    start: "20",
    expressPrice: "0",
    time: "49",
    distant: "6.7",
    comment: ["还会再来", "包装精致"],
    promotion2: ["28减2", "39减5", "65减8"],
  },
  {
    goodImg: "src/assets/img/goods/goods-img3.png",
    title: "顺旺基4",
    score: "4.4",
    salesNumber: "3000+",
    aPrice: "20",
    type: "美团专送",
    start: "20",
    expressPrice: "0",
    time: "49",
    distant: "6.7",
    comment: ["还会再来", "包装精致"],
    promotion2: ["28减2", "39减5", "65减8"],
  },
  {
    goodImg: "src/assets/img/goods/goods-img3.png",
    title: "顺旺基5",
    score: "4.4",
    salesNumber: "3000+",
    aPrice: "20",
    type: "美团专送",
    start: "20",
    expressPrice: "0",
    time: "49",
    distant: "6.7",
    comment: ["还会再来", "包装精致"],
    promotion2: ["28减2", "39减5", "65减8"],
  },
  {
    goodImg: "src/assets/img/goods/goods-img3.png",
    title: "顺旺基6",
    score: "4.4",
    salesNumber: "3000+",
    aPrice: "20",
    type: "美团专送",
    start: "20",
    expressPrice: "0",
    time: "49",
    distant: "6.7",
    comment: ["还会再来", "包装精致"],
    promotion2: ["28减2", "39减5", "65减8"],
  },
  {
    goodImg: "src/assets/img/goods/goods-img3.png",
    title: "顺旺基7",
    score: "4.4",
    salesNumber: "3000+",
    aPrice: "20",
    type: "美团专送",
    start: "20",
    expressPrice: "0",
    time: "49",
    distant: "6.7",
    comment: ["还会再来", "包装精致"],
    promotion2: ["28减2", "39减5", "65减8"],
  },
  {
    goodImg: "src/assets/img/goods/goods-img3.png",
    title: "顺旺基8",
    score: "4.4",
    salesNumber: "3000+",
    aPrice: "20",
    type: "美团专送",
    start: "20",
    expressPrice: "0",
    time: "49",
    distant: "6.7",
    comment: ["还会再来", "包装精致"],
    promotion2: ["28减2", "39减5", "65减8"],
  },
];

export default goodsData;
